/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JOptionPane;


/**
 *
 * @author yagoc
 *//**
 *
 * @author yagoc
 */
public class FormularioProduto extends javax.swing.JFrame {

    /**
     * Creates new form FormulárioProduto
     */
    public FormularioProduto() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 80, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Quantidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 90, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Preço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 150, 80, 22);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(10, 50, 210, 24);
        getContentPane().add(jTextFieldQuantidade);
        jTextFieldQuantidade.setBounds(70, 120, 90, 30);

        jTextFieldPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPreco);
        jTextFieldPreco.setBounds(70, 180, 90, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(60, 230, 100, 32);

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Construção", "Eletrodoméstico", "Eletrônico", "Escolar", "Farmácia", "Infantil", "Limpeza", "Periféricos", "Roupas", " " }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox);
        jComboBox.setBounds(230, 50, 110, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-site.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1, -4, 350, 380);

        setSize(new java.awt.Dimension(366, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       TelaPrincipal telaprincipal = new TelaPrincipal();
        String valor = jComboBox.getSelectedItem().toString();
        if(jComboBox.getSelectedIndex()==0)
        {
             
            Comida comida = new Comida();
            comida.setNome(jTextFieldNome.getText());
            comida.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            comida.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            comida.setTipo("Comida");
            comida.salvar();
            
           JOptionPane.showMessageDialog(null, "Produto salvo!");
           telaprincipal.setVisible(true);
           dispose();
        }
        
        if(jComboBox.getSelectedIndex()==1)
        {
            Construcao construcao = new Construcao();
            construcao.setNome(jTextFieldNome.getText());
            construcao.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            construcao.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            construcao.setTipo("Construção");
            construcao.salvar();
            
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
        if(jComboBox.getSelectedIndex()==2)
        {
            
           Eletrodomestico eletrodomestico = new Eletrodomestico();
            eletrodomestico.setNome(jTextFieldNome.getText());
            eletrodomestico.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            eletrodomestico.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            eletrodomestico.setTipo("Eletrodoméstico");
            eletrodomestico.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
        if(jComboBox.getSelectedIndex()==3)
        {
            Eletronico eletronico = new Eletronico();
            eletronico.setTipo("Eletrônico");
            eletronico.setNome(jTextFieldNome.getText());
            eletronico.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            eletronico.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            eletronico.setTipo("Eletrônico");
            eletronico.salvar();
           JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
                    
        }
        if(jComboBox.getSelectedIndex()==4)
        {
            Escolar escolar = new Escolar();
            escolar.setNome(jTextFieldNome.getText());
            escolar.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            escolar.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            escolar.setTipo("Escolar");
            escolar.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
        if(jComboBox.getSelectedIndex()==5)
        {
            Farmacia farmacia = new Farmacia();
            farmacia.setNome(jTextFieldNome.getText());
            farmacia.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            farmacia.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            farmacia.setTipo("Farmácia");
            farmacia.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
        if(jComboBox.getSelectedIndex()==6)
        {
            Infantil infantil = new Infantil();
            infantil.setNome(jTextFieldNome.getText());
            infantil.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            infantil.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            infantil.setTipo("Infantil");
            infantil.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
        if(jComboBox.getSelectedIndex()==7)
        {
            Limpeza limpeza = new Limpeza();
            limpeza.setNome(jTextFieldNome.getText());
            limpeza.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            limpeza.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            limpeza.setTipo("Limpeza");
            limpeza.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
           dispose();
            
        }
        if(jComboBox.getSelectedIndex()==8)
        {
            Perifericos perifericos = new Perifericos();
            perifericos.setNome(jTextFieldNome.getText());
            perifericos.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            perifericos.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            perifericos.setTipo("Periféricos");
            perifericos.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
        if(jComboBox.getSelectedIndex()==9)
        {
            Roupas roupas = new Roupas();
            roupas.setNome(jTextFieldNome.getText());
            roupas.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            roupas.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            roupas.setTipo("Roupas");
            roupas.salvar();
            JOptionPane.showMessageDialog(null, "Produto salvo!");
            telaprincipal.setVisible(true);
            dispose();
        }
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
      
    }//GEN-LAST:event_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioProduto().setVisible(true);
                          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
