/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yagoc
 */
public class ListaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ListaProdutos
     */
    public ListaProdutos() {
        initComponents();
    }
public  void preencheTabela()
{
    String Nome="";
    String Quantidade="";
    String Preco="";
    String Tipo="";
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    try
    {
     BufferedReader in = new BufferedReader(new FileReader("D:\\Faculdade\\Nova Pasta\\ProjetoEstoque\\produtos.txt"));
    
    File arquivoLeitura = new File("D:\\Faculdade\\Nova Pasta\\ProjetoEstoque\\produtos.txt");  
    LineNumberReader linhaLeitura = new LineNumberReader(new FileReader(arquivoLeitura));  
    linhaLeitura.skip(arquivoLeitura.length());  
    int qtdLinha = linhaLeitura.getLineNumber();  
     int c1=1;
    for (int i=0;i<qtdLinha;i++)
    {
    if (c1==1)
    {
    Nome =  in.readLine();
    
    c1=2;
    }
    else if (c1==2)
    {
    Quantidade =  in.readLine();
    c1=3;
    }
    else if (c1==3)
    {
    Preco =  in.readLine();
    c1=4;
    }
    else if(c1==4)
    {
        Tipo = in.readLine();
        modelo.addRow(new Object[]{Nome,Quantidade,Preco,Tipo});
    c1=1;
    }
    }
    }    
    
    catch(IOException e){
 
    }
} /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Preço", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(-7, 123, 760, 330);

        jButtonRetornar.setText("Retornar");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRetornar);
        jButtonRetornar.setBounds(290, 40, 140, 40);

        setSize(new java.awt.Dimension(776, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed
       TelaPrincipal tp = new TelaPrincipal();
       tp.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ListaProdutos lp = new ListaProdutos();
               lp.preencheTabela();
               lp.setVisible(true);
               
                       
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
