/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author yagoc
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTopicoConstrucao = new javax.swing.JLabel();
        jButtonConstrucao = new javax.swing.JButton();
        jButtonComida = new javax.swing.JButton();
        jLabelTopicoComida = new javax.swing.JLabel();
        jLabelTopicoEletrodomestico = new javax.swing.JLabel();
        jButtonEletronico = new javax.swing.JButton();
        jLabelTopicoEletronico = new javax.swing.JLabel();
        jButtonEletrodomestico = new javax.swing.JButton();
        jButtonEscolar = new javax.swing.JButton();
        jLabelTopicoEscolar = new javax.swing.JLabel();
        jLabelTopicoFarmacia = new javax.swing.JLabel();
        jLabelTopicoInfantil = new javax.swing.JLabel();
        jButtonLimpeza = new javax.swing.JButton();
        jLabelTopicoLimpeza = new javax.swing.JLabel();
        jLabelTopicoPerifericos = new javax.swing.JLabel();
        jLabelTopicoRoupas = new javax.swing.JLabel();
        jButtonRoupas = new javax.swing.JButton();
        jButtonFarmacia = new javax.swing.JButton();
        jButtonInfantil = new javax.swing.JButton();
        jButtonPerifericos = new javax.swing.JButton();
        jButtonLista = new javax.swing.JButton();
        jLabelTopicoLista = new javax.swing.JLabel();
        jLabelTelaFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemComida = new javax.swing.JMenuItem();
        jMenuItemConstrucao = new javax.swing.JMenuItem();
        jMenuItemEletrodomestico = new javax.swing.JMenuItem();
        jMenuItemEletronico = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemFarmacia = new javax.swing.JMenuItem();
        Infantil = new javax.swing.JMenuItem();
        jMenuItemLimpeza = new javax.swing.JMenuItem();
        jMenuItemPerifericos = new javax.swing.JMenuItem();
        jMenuItemRoupas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTopicoConstrucao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoConstrucao.setText("Construção");
        getContentPane().add(jLabelTopicoConstrucao);
        jLabelTopicoConstrucao.setBounds(190, 20, 100, 22);

        jButtonConstrucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone material de construção.png"))); // NOI18N
        jButtonConstrucao.setToolTipText("Cadastrar Material de Construção ");
        jButtonConstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConstrucaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConstrucao);
        jButtonConstrucao.setBounds(190, 60, 100, 100);

        jButtonComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone comida.png"))); // NOI18N
        jButtonComida.setToolTipText("Cadastrar Comida");
        jButtonComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComida);
        jButtonComida.setBounds(50, 60, 100, 100);

        jLabelTopicoComida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoComida.setText("Comida");
        getContentPane().add(jLabelTopicoComida);
        jLabelTopicoComida.setBounds(60, 20, 70, 22);

        jLabelTopicoEletrodomestico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoEletrodomestico.setText("Eletrodoméstico");
        getContentPane().add(jLabelTopicoEletrodomestico);
        jLabelTopicoEletrodomestico.setBounds(330, 20, 140, 22);

        jButtonEletronico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone eletronico.png"))); // NOI18N
        jButtonEletronico.setToolTipText("Cadastrar Eletrônico");
        jButtonEletronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEletronicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEletronico);
        jButtonEletronico.setBounds(490, 60, 100, 100);

        jLabelTopicoEletronico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoEletronico.setText("Eletrônico");
        getContentPane().add(jLabelTopicoEletronico);
        jLabelTopicoEletronico.setBounds(500, 20, 140, 22);

        jButtonEletrodomestico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone eletrodomestico.png"))); // NOI18N
        jButtonEletrodomestico.setToolTipText("Cadastrar Eletrodoméstico");
        jButtonEletrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEletrodomesticoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEletrodomestico);
        jButtonEletrodomestico.setBounds(340, 60, 100, 100);

        jButtonEscolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone escolar.png"))); // NOI18N
        jButtonEscolar.setToolTipText("Cadastrar material escolar");
        jButtonEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscolarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEscolar);
        jButtonEscolar.setBounds(660, 60, 100, 100);

        jLabelTopicoEscolar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoEscolar.setText("Escolar");
        getContentPane().add(jLabelTopicoEscolar);
        jLabelTopicoEscolar.setBounds(670, 20, 140, 22);

        jLabelTopicoFarmacia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoFarmacia.setText("Farmácia");
        getContentPane().add(jLabelTopicoFarmacia);
        jLabelTopicoFarmacia.setBounds(60, 180, 70, 22);

        jLabelTopicoInfantil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoInfantil.setText("Infantil");
        getContentPane().add(jLabelTopicoInfantil);
        jLabelTopicoInfantil.setBounds(210, 180, 100, 22);

        jButtonLimpeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone limpeza.png"))); // NOI18N
        jButtonLimpeza.setToolTipText("Cadastrar material de limpeza");
        jButtonLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpezaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpeza);
        jButtonLimpeza.setBounds(330, 220, 110, 110);

        jLabelTopicoLimpeza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoLimpeza.setText("Limpeza");
        getContentPane().add(jLabelTopicoLimpeza);
        jLabelTopicoLimpeza.setBounds(350, 180, 140, 22);

        jLabelTopicoPerifericos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoPerifericos.setText("Periféricos");
        getContentPane().add(jLabelTopicoPerifericos);
        jLabelTopicoPerifericos.setBounds(500, 180, 140, 22);

        jLabelTopicoRoupas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoRoupas.setText("Roupas");
        getContentPane().add(jLabelTopicoRoupas);
        jLabelTopicoRoupas.setBounds(670, 180, 140, 22);

        jButtonRoupas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone roupa.png"))); // NOI18N
        jButtonRoupas.setToolTipText("Cadastrar roupas");
        jButtonRoupas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoupasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRoupas);
        jButtonRoupas.setBounds(650, 220, 100, 100);

        jButtonFarmacia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone farmácia.png"))); // NOI18N
        jButtonFarmacia.setToolTipText("Cadastrar medicamentos");
        jButtonFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFarmaciaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFarmacia);
        jButtonFarmacia.setBounds(50, 220, 100, 100);

        jButtonInfantil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone infantil.png"))); // NOI18N
        jButtonInfantil.setToolTipText("Cadastrar produto infantil");
        jButtonInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfantilActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInfantil);
        jButtonInfantil.setBounds(190, 220, 110, 100);

        jButtonPerifericos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone mouse.png"))); // NOI18N
        jButtonPerifericos.setToolTipText("Cadastrar periféricos");
        jButtonPerifericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerifericosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPerifericos);
        jButtonPerifericos.setBounds(470, 220, 110, 110);

        jButtonLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone lista.png"))); // NOI18N
        jButtonLista.setToolTipText("Checar a lista de produtos ");
        jButtonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLista);
        jButtonLista.setBounds(340, 380, 130, 100);

        jLabelTopicoLista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTopicoLista.setText("Lista de Produtos");
        getContentPane().add(jLabelTopicoLista);
        jLabelTopicoLista.setBounds(340, 340, 160, 30);

        jLabelTelaFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-site.jpg"))); // NOI18N
        getContentPane().add(jLabelTelaFundoPrincipal);
        jLabelTelaFundoPrincipal.setBounds(0, 0, 2048, 903);

        jMenuCadastros.setText("Cadastros");

        jMenuItemComida.setText("Comida");
        jMenuCadastros.add(jMenuItemComida);

        jMenuItemConstrucao.setText("Construção");
        jMenuCadastros.add(jMenuItemConstrucao);

        jMenuItemEletrodomestico.setText("Eletrodoméstico");
        jMenuItemEletrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEletrodomesticoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemEletrodomestico);

        jMenuItemEletronico.setText("Eletrônico");
        jMenuCadastros.add(jMenuItemEletronico);

        jMenuItem4.setText("Escolar");
        jMenuCadastros.add(jMenuItem4);

        jMenuItemFarmacia.setText("Farmácia");
        jMenuItemFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFarmaciaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFarmacia);

        Infantil.setText("Infantil");
        jMenuCadastros.add(Infantil);

        jMenuItemLimpeza.setText("Limpeza");
        jMenuCadastros.add(jMenuItemLimpeza);

        jMenuItemPerifericos.setText("Periféricos");
        jMenuCadastros.add(jMenuItemPerifericos);

        jMenuItemRoupas.setText("Roupas");
        jMenuCadastros.add(jMenuItemRoupas);

        jMenuBar1.add(jMenuCadastros);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(841, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEletrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEletrodomesticoActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemEletrodomesticoActionPerformed

    private void jMenuItemFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFarmaciaActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemFarmaciaActionPerformed

    private void jButtonEletrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEletrodomesticoActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEletrodomesticoActionPerformed

    private void jButtonEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscolarActionPerformed
       FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButtonEscolarActionPerformed

    private void jButtonLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpezaActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLimpezaActionPerformed

    private void jButtonRoupasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoupasActionPerformed
        FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRoupasActionPerformed

    private void jButtonComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComidaActionPerformed
        FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonComidaActionPerformed

    private void jButtonConstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConstrucaoActionPerformed
      FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonConstrucaoActionPerformed

    private void jButtonEletronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEletronicoActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEletronicoActionPerformed

    private void jButtonFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFarmaciaActionPerformed
        FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFarmaciaActionPerformed

    private void jButtonInfantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfantilActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInfantilActionPerformed

    private void jButtonPerifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerifericosActionPerformed
         FormularioProduto fp = new FormularioProduto();
        fp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPerifericosActionPerformed

    private void jButtonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaActionPerformed
        ListaProdutos lp = new ListaProdutos();
        lp.setVisible(true);
        lp.preencheTabela();
        dispose();
    }//GEN-LAST:event_jButtonListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Infantil;
    private javax.swing.JButton jButtonComida;
    private javax.swing.JButton jButtonConstrucao;
    private javax.swing.JButton jButtonEletrodomestico;
    private javax.swing.JButton jButtonEletronico;
    private javax.swing.JButton jButtonEscolar;
    private javax.swing.JButton jButtonFarmacia;
    private javax.swing.JButton jButtonInfantil;
    private javax.swing.JButton jButtonLimpeza;
    private javax.swing.JButton jButtonLista;
    private javax.swing.JButton jButtonPerifericos;
    private javax.swing.JButton jButtonRoupas;
    private javax.swing.JLabel jLabelTelaFundoPrincipal;
    private javax.swing.JLabel jLabelTopicoComida;
    private javax.swing.JLabel jLabelTopicoConstrucao;
    private javax.swing.JLabel jLabelTopicoEletrodomestico;
    private javax.swing.JLabel jLabelTopicoEletronico;
    private javax.swing.JLabel jLabelTopicoEscolar;
    private javax.swing.JLabel jLabelTopicoFarmacia;
    private javax.swing.JLabel jLabelTopicoInfantil;
    private javax.swing.JLabel jLabelTopicoLimpeza;
    private javax.swing.JLabel jLabelTopicoLista;
    private javax.swing.JLabel jLabelTopicoPerifericos;
    private javax.swing.JLabel jLabelTopicoRoupas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemComida;
    private javax.swing.JMenuItem jMenuItemConstrucao;
    private javax.swing.JMenuItem jMenuItemEletrodomestico;
    private javax.swing.JMenuItem jMenuItemEletronico;
    private javax.swing.JMenuItem jMenuItemFarmacia;
    private javax.swing.JMenuItem jMenuItemLimpeza;
    private javax.swing.JMenuItem jMenuItemPerifericos;
    private javax.swing.JMenuItem jMenuItemRoupas;
    // End of variables declaration//GEN-END:variables
}
